---
# author: xxx

- name: Install a list of packages (nginx)
  apt:
    pkg:
      - nginx

- name: Push nginx configuration
  template: src=xxx.j2 dest=/etc/nginx/sites-enabled/xxx mode=0640 owner=root group=root
  notify: 
    - Restart nginx 

# - name: Restarting nginx
#   command: service nginx restart










